server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: userservice
          uri: http://localhost:8084/
          predicates:
            - Path=/api/user/**
        - id: chatservice
          uri: http://localhost:8092/
          predicates:
            - Path=/api/chat/**
        - id: boardservice
          uri: http://localhost:8086/
          predicates:
            - Path=/api/board/**
