
server:
  port: 8086
spring:
  application:
    name: boardservice

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gcumall?createDatabaseIfNotExist=true&useUnicode=true&charaterEncoding=UTF-8&characterSetResults=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: cbxd2525
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create

  data:
    rest:
      base-path: /api
      default-page-size: 10
      max-page-size: 10

eureka:
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30

  client:
    registerWithEureka: true
    fetchRegistry: true

  serviceUrl:
    defaultZone: http://127.0.0.1:8761/eureka/